apiVersion: v1
kind: Service
metadata:
  name: personal-page-service
spec:
  type: LoadBalancer
  loadBalancerIP: 130.211.132.98
  ports:
    - port: 80
      name: "http"
    - port: 443
      name: "https"
  selector:
    name: personal-page-pod
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: personal-page-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: personal-page-pod
    spec:
      containers:
        - name: personal-page
          image: gcr.io/acristoffers-me/personal-page:v8
          ports:
            - containerPort: 80
            - containerPort: 443
