# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@webcomponents/custom-elements-1.6.0" = {
      name = "_at_webcomponents_slash_custom-elements";
      packageName = "@webcomponents/custom-elements";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webcomponents/custom-elements/-/custom-elements-1.6.0.tgz";
        sha512 = "CqTpxOlUCPWRNUPZDxT5v2NnHXA4oox612iUGnmTUGQFhZ1Gkj8kirtl/2wcF6MqX7+PqqicZzOCBKKfIn0dww==";
      };
    };
    "elm-keyboard-shortcut-1.0.1" = {
      name = "elm-keyboard-shortcut";
      packageName = "elm-keyboard-shortcut";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/elm-keyboard-shortcut/-/elm-keyboard-shortcut-1.0.1.tgz";
        sha512 = "AlEfAshBOPz429YIQjaNd1GGl+6RCBLntKvuuK+/G0Buvq0B048bs1NXoQKRZDlgJGPPCi2LEscHomHk+P42zw==";
      };
    };
    "lodash.deburr-4.1.0" = {
      name = "lodash.deburr";
      packageName = "lodash.deburr";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.deburr/-/lodash.deburr-4.1.0.tgz";
        sha512 = "m/M1U1f3ddMCs6Hq2tAsYThTBDaAKFDX3dwDo97GEYzamXi9SqUpjWi/Rrj/gf3X2n8ktwgZrlP1z6E3v/IExQ==";
      };
    };
    "typescript-4.9.5" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz";
        sha512 = "1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==";
      };
    };
  };
  args = {
    name = "personal-page";
    packageName = "personal-page";
    src = ./..;
    dependencies = [
      sources."@webcomponents/custom-elements-1.6.0"
      sources."elm-keyboard-shortcut-1.0.1"
      sources."lodash.deburr-4.1.0"
      sources."typescript-4.9.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
